@startuml
!pragma layout smetana

' Domænemodel for Java Quiz Applikation

object Quiz
object Question
object Answer
object Score
object UserResponse
object Category
object Database

' Komposition - Quiz består af Questions
Quiz *-- Question

' Komposition - Question består af Answers
Question *-- Answer

' Association - Quiz tracker Score
Quiz -- Score

' Association - Question tilhører Category
Question -- Category

' Association - Question modtager UserResponse
Question -- UserResponse

' Dependency - DatabaseManager håndterer data
Database ..> Quiz
Database ..> Question
Database ..> Answer



@enduml


@startuml
!pragma layout smetana
class Player {
  name
  score
}

class Quiz {
  player
  questions
}

class Question {
  questionText
  options
  correctAnswer
}

Player -- Quiz
Quiz -- Question

@enduml